import { defineConfig } from "oxfmt";

export default defineConfig({
  ignorePatterns: [
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".omp/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".scratch/**",
    ".windsurf/**",
    "android/**",
    "docs/**",
    "*.md",
    "dist/**",
    "examples/**/lynx-dist/**",
    "examples/**/host-dist/**",
    "examples/**/node_modules/**",
    "examples/**/.rspeedy/**",
    "ios/**",
    "lynxtron/**",
    "native-vendor/**",
    "node_modules/**",
    "scripts/**",
    "shared/**",
    "third_party/**",
    "tools/oxlint/anti-slop/**",
  ],
});
